### ISSUE TITLE
Viewport is not highlight properly when the element is  below the viewport 

### ISSUE THREAD

**Issue by deepaksmarterdharma** [elrumordelaluz/reactour#454] opened 2022-03-08 02:22 UTC
The button to trigger the tour is in my sidebar but the highlighted element is on the very last of the page which we have to scroll down to. So when i click on the show tour button it scroll down to that element but does not highlight it and the background is blurred.

**Comment by deepaksmarterdharma** [comment] 2022-03-08 02:26
`  <Tour
          {...tourProps}
          lastStepNextButton={
            <Button style={{ color: '#29E1AC', marginLeft: '150%', marginTop: '-60px', backgroundColor: '#FFFFFF', fontSize: '12px' }} onClick={handleEnd}>
              End
            </Button>
          }
          disableKeyboardNavigation={['esc']}
          showNavigation={false}
          showNumber={false}
          startAt={0}
          prevButton
          nextButton={<Button style={{ color: '#29E1AC', backgroundColor: '#FFFFFF', marginLeft: '150%', fontSize: '12px', marginTop: '-10px' }}>Next</Button>}
          disableInteraction={true}
          badgeContent={(curr, tot) => `${curr} of ${tot}`}
          rounded={12}
          maskClassName="mask"
          className="helper"
          scrollDuration="300"
          // onAfterOpen={disableBody}
          // onBeforeClose={enableBody}
        />`

**Comment by deepaksmarterdharma** [comment] 2022-03-08 02:26
`  <Tour
          {...tourProps}
          lastStepNextButton={
            <Button style={{ color: '#29E1AC', marginLeft: '150%', marginTop: '-60px', backgroundColor: '#FFFFFF', fontSize: '12px' }} onClick={handleEnd}>
              End
            </Button>
          }
          disableKeyboardNavigation={['esc']}
          showNavigation={false}
          showNumber={false}
          startAt={0}
          prevButton
          nextButton={<Button style={{ color: '#29E1AC', backgroundColor: '#FFFFFF', marginLeft: '150%', fontSize: '12px', marginTop: '-10px' }}>Next</Button>}
          disableInteraction={true}
          badgeContent={(curr, tot) => `${curr} of ${tot}`}
          rounded={12}
          maskClassName="mask"
          className="helper"
          scrollDuration="300"
          // onAfterOpen={disableBody}
          // onBeforeClose={enableBody}
          // startAt={0}
        />`

**Comment by elrumordelaluz** [comment] 2022-03-08 11:53
Hi @deepaksmarterdharma, thanks for open the _Issue_.

Mind creating a sandbox reproducing the issue. However I suggest you to migrate into `v2` using `@reactour/tour` and its new api, which handles better those kind of situations.

**Comment by deepaksmarterdharma** [comment] 2022-03-08 12:52
Thanks for the reply, Okay let me try the reactour/tour. If that does not solve the issue i will reopen this conversation.

**Comment by elrumordelaluz** [comment] 2022-03-08 13:41
cool, thank you!

So I closing for now but feel free to re-open or create a new _Issue_.

**Closed by elrumordelaluz** 2022-03-08 13:41 UTC
Labels: bug

**Comment by devaeshtech** [comment] 2023-03-26 07:25
![image](https://user-images.githubusercontent.com/125268157/227761510-a9390cc7-fed0-4c67-8c94-fe85e7ceaf3e.png)

**Comment by devaeshtech** [comment] 2023-03-26 07:27
![image](https://user-images.githubusercontent.com/125268157/227761541-512d783d-e118-4248-942b-4e2a7dafa8a1.png)

**Mask is not highlighting element completely because it not scroll completely to top when press back!**
