### ISSUE TITLE
How to handle Mobile Keyboard when an input is selected

### ISSUE THREAD

**Issue by LordA98** [elrumordelaluz/reactour#338] opened 2021-04-14 20:59 UTC
Hi,

I'm trying to make my tour more mobile friendly.

One issue I am facing is this:

When a step that involves a text input is started, the tour popup or _Helper_ (I think this is what it's called) navigates to the input via it's _selector_.  When the input is clicked or tapped, the keyboard rises from the bottom of the screen.  

This is where the problem occurs - on smaller devices, the now on-screen keyboard forces the tour _Helper_ (?) onto the top of the screen, often overlapping the input that needs to be typed into.  Although the user can technically still still type, they have no real indication of what they are typing as they cannot see it.

Is there a way to cater for this?  Either by hiding the _Helper_ or removing all text content in it to make it shorter and hence not take up the rest of the screen?

Would appreciate any help.

Thanks,
Alex

**Comment by elrumordelaluz** [comment] 2021-04-16 09:05
Hi @LordA98, thanks for open the _Issue_.

Pretty interesting what you are describing. Mind create a small reproduction in a sandbox, in order to try and debug it? or at list share a screenshot of the result? thanks

**Comment by djaffer** [comment] 2021-09-30 03:21
same issue here if the interaction is allowed on the input field and keyboard gets open the highlight gets out of focus.

**Comment by elrumordelaluz** [comment] 2021-09-30 07:15
Please consider create a minimal reproduction in a sandbox in order to debug and analyze this use-case. Thanks!

**Comment by djaffer** [comment] 2021-09-30 19:12
It is in mobile so cannot really do it on codesandbox.
![reacttour](https://user-images.githubusercontent.com/5740725/135516415-570a4525-7037-448c-8f00-86257370484a.gif)

**Comment by elrumordelaluz** [comment] 2021-10-01 05:51
Ok, however super clear the situation, need to stop auto-position, when _keyboard_ opens, or at least scroll to element again. Let's investigate.

**Comment by elrumordelaluz** [comment] 2021-10-01 10:54
Thank you @djaffer to share the screecast, can you share the part of `steps` involved, and the version of the library you are using?

**Comment by djaffer** [comment] 2021-10-01 22:37
version: 1.18.6

**Comment by elrumordelaluz** [comment] 2021-10-02 06:47
Could you please try upgrading to `@reactour/tour`, like [here](https://codesandbox.io/s/reactour-tour-demo-using-react-modal-forked-i7gbt?file=/components/Main.js)?

https://user-images.githubusercontent.com/784056/135706629-65862b9d-a1cb-4ee4-9934-cdfb0b7dedb0.mp4

**Comment by djaffer** [comment] 2021-10-02 22:07
I am using a class component an example of how to use the one above in class. Also, any workaround anything available. Thank you for being proactive in helping.

**Comment by elrumordelaluz** [comment] 2021-10-04 08:50
@djaffer please update into `@reactour/tour@2.1.0` which exports [withTour HoC](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#withtour) allowing you to use all `useTour` hook props from your React.Component. [Here](https://reactour.vercel.app/#higher-order-component) is an example online.

**Comment by djaffer** [comment] 2021-10-05 08:37
thanks! I looked at it. It is not possible to change the entire flow to this because we have validation, etc for the flow. Is there a way to have the next step and prev step handler in the child component?

**Comment by djaffer** [comment] 2021-10-05 08:37
thanks! I looked at it. It is not possible to change the entire flow to this because we have validation, etc for the flow. Is there a way to have next step and prec handler in the child component.

**Comment by elrumordelaluz** [comment] 2021-10-05 09:07
> Is there a way to have the next step and prev step handler in the child component?

Using `useTour`?

**Comment by djaffer** [comment] 2021-10-05 18:45
usetour we can't use because it is a class component. A suggestion would be this could be fixed in the 1.18.6 or you can tell me work around hack for me to get this to work. We can schedule the migration to this as a side note.

**Comment by elrumordelaluz** [comment] 2021-10-06 07:21
You can user `withTour` in each component and handle the next/prev behavior throug `setCurrentStep`. Could you please share a peace of code in order to understand better?

> All props that are currently used will have to be migratable.

Agree, let me know what you think are missing (it is absolutely possible), because some use cases are solvable in new ways, allowing to have less config props in the main _Tour_, thanks!

**Comment by djaffer** [comment] 2021-10-06 08:03
Thanks for response. Please can you get the in the child component way to add next, prev button handler for the controlled use case? In your [example](https://reactour.vercel.app/#higher-order-component), it would be inside the Placeholder component. I do not think right now you have this. Maybe you can add something props to set the next handler.


              nextStep={this.tourNextStepHandler.bind(this)}
              prevStep={this.tourPrevStepHandler.bind(this)}

**Comment by elrumordelaluz** [comment] 2021-10-06 08:16
In this example, the _Placeholder_ component is the one enhanced with `withTour` and it is a child component of _TourProvider_. I am missing something?

**Comment by djaffer** [comment] 2021-10-08 23:37
any update @elrumordelaluz ?

**Comment by djaffer** [comment] 2021-10-13 20:17
any update @elrumordelaluz ?

**Comment by djaffer** [comment] 2021-10-31 10:23
any update @elrumordelaluz ?

**Comment by elrumordelaluz** [comment] 2021-11-01 20:53
I'm sorry @djaffer, couldn't get an eye on this yet. Will try to this week. Any help welcome.

**Comment by djaffer** [comment] 2021-11-10 05:08
Would be happy to help but I am not too familiar with the structure of this.  Currently, I decided not to use this feature just to show the steps and not have interaction enabled. Mandating to use hooks for the older code is a challenge.

**Comment by elrumordelaluz** [comment] 2021-11-10 08:05
Hi @djaffer, I am sorry, but couldn't give the attention needed for this issue yet. Thank you anyway for the desire to help. Will get back to you as soon as solved it in any way.

**Comment by elrumordelaluz** [comment] 2021-12-21 16:09
@djaffer Since the point of the issue was switched I am closing this _issue_ and will track progress in #415

**Closed by elrumordelaluz** 2021-12-21 16:09 UTC
