### ISSUE TITLE
Uncaught ReferenceError: React is not defined in production build using vite

### ISSUE THREAD

**Issue by robiokidenis** [elrumordelaluz/reactour#514] opened 2022-10-27 14:06 UTC
I get an Uncaught `ReferenceError: React is not defined error`. This error happens only in production build and not in the dev server.

here is my vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    
    plugins: [
        laravel({
            input: 'resources/js/app.jsx',
            refresh: true,
        }),
        react(),
    ],
    
});
```

**Comment by elrumordelaluz** [comment] 2022-10-27 16:41
Hi @robiokidenis, thanks for open the _Issue_.

Mind creating a minimal reproduction in a sandbox in order to allow others to debug your use-case and try to find a solution? Thanks!

**Comment by robiokidenis** [comment] 2022-10-27 17:13
Hi @elrumordelaluz, thanks for the quick response,
The good news, after I made minimal reproduction and changed react version from 17.0.2 to 18.2.0 and also change npm to yarn, it works fine

this is the repo I used for testing
[minimal reproduction](https://github.com/robiokidenis/test-reacttour-vite)

**Comment by FedeG** [comment] 2022-11-23 16:43
Hi, @elrumordelaluz and @robiokidenis 

I have the same problem but the workaround of upgrade react isn't working for me.
I added sourcemap files to `vite build` and the error raised in this line: https://github.com/elrumordelaluz/reactour/blob/main/packages/tour/Tour.tsx#L111

My workaround was sent the `Wrapper` props with `Fragment` as value.

**Comment by robiokidenis** [comment] 2022-11-24 01:54
Hi @FedeG ,
could you try to remove the node_modules directory first and then run yarn, this is work for me

**Comment by gordonmckenzie** [comment] 2023-02-09 22:53
I also had the exact same problem, fixed by suggestion from @FedeG.

**Comment by sanblu** [comment] 2023-03-25 23:01
Same problem here, fix suggested by @FedeG  as follows:
`        <TourProvider
          **Wrapper={React.Fragment}**
          steps={steps}
`

**Comment by skala2301** [comment] 2024-07-10 19:41
same problem and fixed as suggested by @FedeG 
`<TourProvider
                    steps = {[]}
                    ...
                    ...
                    Wrapper={Fragment}
  >`

**Comment by elrumordelaluz** [comment] 2024-07-16 16:37
closing since seems solved.

**Closed by elrumordelaluz** 2024-07-16 16:37 UTC
