### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by engmagdy87** [elrumordelaluz/reactour#79] opened 2018-10-14 21:50 UTC
React 16 raise this error:
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
and this is my step
```
[
     ,{
      selector: ".step3",
      content: () => (
        <div>
          <strong>
             Hello
            <span role="img" aria-label="">
              🤖
            </span>
          </strong>
          This is step 3
        </div>
      )
    },
]
```

**Comment by elrumordelaluz** [comment] 2019-05-22 08:14
Closing since hadn't further info to reproduce or analyze the problem. Feel free to re-open or open a new one in any case.

**Closed by elrumordelaluz** 2019-05-22 08:14 UTC
Labels: need-more-info
