### ISSUE TITLE
Need a way to delay highlighting until an element is in the DOM

### ISSUE THREAD

**Issue by RobertGary1** [elrumordelaluz/reactour#170] opened 2019-09-04 22:35 UTC
I have several cases where a click on the page causes something to be rendered into the DOM but because the pathname doesn't change the tour either highlights the wrong thing or just misses it because it renders before the new element. Would be nice if you could specify to wait until the selector element is in the DOM.

**Comment by RobertGary1** [comment] 2019-09-05 00:22
Hmm, I see an undocumented parameter to step "observe". I wonder if that could help.

**Comment by aqarain** [comment] 2019-09-18 22:58
What you can do is you can assign a reference to the element which you want to be there in the DOM. Once the element is there in DOM, you can assign it to an observable and use useEffect again to call goTo(curr +1); so for e.g.

```
const ref = React.useRef(null);
const [elem, setElement] = React.useState(false)
React.useEffect(() => {
   ref.current ? setElement(true) : null;
})

React.useEffect(() => {
   //Go to next step once elem is there in DOM
    goTo(curr+1);
}, [elem])


<div ref={ref} />


```

**Comment by RobertGary1** [comment] 2019-09-18 23:57
I've pushed up a PR 184 that fixes this easily. I've included it in my repo and released under reactour2 in npm. If this repo because active again I'll deprecate mine.

**Comment by aqarain** [comment] 2019-09-19 11:51
Do you know how we can add outlined div boxes instead of just a rectangular div?

**Comment by RobertGary1** [comment] 2019-09-19 18:18
There is no option for that now that I know of but it wouldn't be a difficult enhancement oryou could override the style. You could probably add it to style .reactour__helper

**Comment by vemuez** [comment] 2019-10-14 13:00
I'm not too sure whether this would be categorised as the same issue. The way I use reactour is as a help guide that can be access from the navbar. 

Each page that would require a guide would have its own steppers. Pressing the help button on the navbar would trigger the relevant steps. However, the problem that i'm having is that during async requests, I use `observe` in the stepper to observe any changes so that when actual data comes through, it would be able to select the element as soon as the observe detects the change...

Here's a small reproduction of the issue: https://stackblitz.com/edit/react-xaev9z?file=index.js

**Comment by elrumordelaluz** [comment] 2022-01-28 10:02
Due to inactivity I am closing this _issue_, but feel free to re-open or create a new one in any case.

**Closed by elrumordelaluz** 2022-01-28 10:02 UTC

**Comment by ces-hoangdao** [comment] 2023-03-23 03:46
I face this issue any solution for it

**Comment by FrancisBrokering** [comment] 2023-05-06 04:48
Having the same problem...

**Comment by usamamajid6** [comment] 2024-02-21 03:00
Try using 
'inViewThreshold' prop
