### ISSUE TITLE
1.8.6 application crash with Uncaught SyntaxError

### ISSUE THREAD

**Issue by aaronccasanova** [elrumordelaluz/reactour#72] opened 2018-08-27 18:26 UTC
After updating to 1.8.6 my application crashes on startup with the following console error. I reverted back to 1.8.2 and everything is working as expected.

<img width="1398" alt="screen shot 2018-08-27 at 11 15 25 am" src="https://user-images.githubusercontent.com/32409546/44677391-a75afe80-a9ea-11e8-896e-5e41cc18bd99.png">

**Comment by aaronccasanova** [comment] 2018-08-27 18:30
Not sure if this is a factor, but we are running on react 15.6.2

**Comment by elrumordelaluz** [comment] 2018-08-27 21:42
hi @aaronccasanova, thanks for the _Issue_.
reverting to `1.8.5` didn't work? 

Don't seem related to this, but since `1.8.6` you need to [install `styled-components` separately](https://github.com/elrumordelaluz/reactour#install).

**Comment by pojrzynski** [comment] 2018-08-28 06:59
I have the same issue with version 1.8.6. Using react 16.4.2. Styled components are installed separately.

**Comment by elrumordelaluz** [comment] 2018-08-28 07:03
hi @pojrzynski, did you try with `1.8.5`? Asking to know if the issue comes from the last changes.

could you share the error details and something about the stack structure? (ideally a repo/snippet) 

Yesterday I created [this repo](https://github.com/elrumordelaluz/reactour-test) to test those things but everything seems work well.

Please let me know,

**Comment by pojrzynski** [comment] 2018-08-28 07:06
Hey, yes I used 1.8.5 and don't see this error, but I have other issues with this version. It seems that this version removes some of my styled components definitions and breaks my layout.

**Comment by elrumordelaluz** [comment] 2018-08-28 07:48
@pojrzynski Do you have a repo to share?

> but I have other issues with this version

Probably related on [this](https://github.com/elrumordelaluz/reactour/issues/59#issuecomment-405783526)

**Comment by elrumordelaluz** [comment] 2018-09-04 15:07
I am curious if in both _Applications_ are you using `styled-components` other than with `reactour`? In that case, could you please try `rm -rf node_modules && yarn`? Thanks in advance.

I continued trying in different kind of applications, _Webpack_ versions etc but can't reproduce what happens in your cases.

**Comment by trangtv04110** [comment] 2018-09-06 07:27
I have the same issue

**Comment by elrumordelaluz** [comment] 2018-09-06 07:46
@trangtv04110 do you have a repo or a way to share a reproduction of the _issue_?

**Comment by trangtv04110** [comment] 2018-09-06 08:06
hi @elrumordelaluz , I tried with create-react-app and your module works fine.
But when I add it to my current private project, it display the error like the above image.
I'm not sure what's wrong

**Comment by elrumordelaluz** [comment] 2018-09-06 08:16
> But when I add it to my current private project

Could you please share your `package.json` file?

**Comment by elrumordelaluz** [comment] 2018-09-06 08:27
thank you @trangtv04110, what results if you try `npm ls styled-components` on your project directory?

**Comment by trangtv04110** [comment] 2018-09-06 08:29
@elrumordelaluz  styled-components@3.4.5

**Comment by elrumordelaluz** [comment] 2018-09-06 08:32
ok, so no other _packages_ bundling SC at all, thank you

**Comment by elrumordelaluz** [comment] 2018-09-06 09:09
@aaronccasanova @trangtv04110 @pojrzynski could you please try with `reactour@1.8.7`? 

should be fixed, please let me know.

**Comment by elrumordelaluz** [comment] 2018-09-06 09:27
awesome, closing the _issue_.
feel free to re-open in any case.

**Closed by elrumordelaluz** 2018-09-06 09:27 UTC
Labels: need-more-info
