### ISSUE TITLE
Mask not showing on Edge with Windows scalability

### ISSUE THREAD

**Issue by LucasVancoIBM** [elrumordelaluz/reactour#380] opened 2021-09-27 13:28 UTC
Hello, I have the exact same problem explained in #369 .
The masks are not being displayed correctly and the whole page is black.
I am using Edge on Windows with a scalability of 125%. It is an enterprise computer so I can not change any settings.
(If I change the scalability to 100% it works fine, but it is not a solution for me)

Do you have any idea on how I can solve that problem only using code please ?

**Comment by elrumordelaluz** [comment] 2021-09-27 17:10
Hi @LucasVancoIBM, thanks for open the _Issue_. 

I will try to reproduce the issue in a windows machine, since I already tried on mac and couldn't get that result.

**Comment by LucasVancoIBM** [comment] 2021-09-28 11:56
Thank you for your quick reply.
To easily reproduce the bug and test it, you can just use your own codesandbox example, the first one with react router. I am able to reproduce both on Edge and Chrome with a scalability of 125%.

Thanks in advance for your help.

**Comment by elrumordelaluz** [comment] 2021-09-28 17:45
I had the opportunity to test on that sandbox and noted that the version of `@reactour/tour` was an old one. Updating it fix the issue for me. Could you please try updating into `v2.0.1`, just refreshing it in the `package.json`? However I'll update from my side to avoid this.

Anyway, are you having the same issue in your project also? In that case, mind sharing a minimal reproduction in a sandbox?

**Comment by LucasVancoIBM** [comment] 2021-09-29 16:37
Yes i have the issue inside my own project even after upgrading the version to `2.0.1` in the `package.json` file.

The project is pretty huge and I don't think I am going to be able to reproduce it in a sandbox. But it is a simple tour with 10 steps and nothing fancy. 
Here is the code implementing the Tour : 
`
const styles = {
    popover: base => ({
        ...base,
        borderRadius: '10px',
        '--reactour-accent': '#017c4c',
    }),
    dot: base => ({
        ...base,
        '&:focus': {
            outline: 'none'
        }
    }),
    close: base => ({
        ...base,
        '&:focus': {
            outline: 'none'
        }
    }),
    button: base => ({
        ...base,
        '&:focus': {
            outline: 'none'
        }
    })
}

ReactDOM.render(
    <Provider store={store}>
        <TourProvider
            steps={steps}
            disableInteraction={true}
            badgeContent={({ totalSteps, currentStep }) => `${currentStep + 1}/${totalSteps}`}
            styles={styles}
            // disable closing tour from clicking outside the popover
            onClickMask={() => null}
            // customize next button to show 'close' text for last step
            nextButton={({
                 Button,
                 currentStep,
                 stepsLength,
                 setIsOpen,
                 setCurrentStep
            }) => {
                const last = currentStep === stepsLength - 1;
                return (
                    <Button
                        hideArrow={last}
                        onClick={() => {
                            if (last) {
                                setIsOpen(false)
                            } else {
                                setCurrentStep(s => (s === steps.length - 1 ? 0 : s + 1))
                            }
                        }}
                    >
                        {last ? 'Close' : null}
                    </Button>
                )
            }}
        >
            <Home />
        </TourProvider>
    </Provider>
    , document.getElementById('generator'));
`

**Comment by elrumordelaluz** [comment] 2021-09-29 17:09
> To easily reproduce the bug and test it, you can just use your own codesandbox example, the first one with react router.

Are you also already having the issue in the sandbox?

**Comment by LucasVancoIBM** [comment] 2021-09-30 12:26
It seems that the problem no longer appear on my enterprise computer with this sandbox. 
Can you explain to me what changes you made ?

**Comment by elrumordelaluz** [comment] 2021-09-30 13:04
so weird, I only upgraded the `@reactour/tour` version.

Mind create a minimal sandbox, without the complexity of your project, but with zoom 125%, trying to understand at what point the _Mask_ stops working.

Super curious on what's the issue.

**Comment by LucasVancoIBM** [comment] 2021-09-30 13:16
The thing is that the zoom is handled directly by Windows and not by the browser or the code so I do not have control over it.

**Comment by LucasVancoIBM** [comment] 2021-09-30 13:27
I noticed that in my `package.json` I have this `"@reactour/tour": "^2.0.1"` whereas inside the sandbox it is `"@reactour/tour": "2.0.1"`, do you think it makes a difference ? 
And also my react version is `"react": "^16.12.0"` and `"react": "17.0.2"` for the sandbox, can it be the cause ?

**Comment by elrumordelaluz** [comment] 2021-09-30 13:28
Are you able to update the react version?

**Comment by elrumordelaluz** [comment] 2021-09-30 13:29
Or try downgrading from the sandbox?

**Comment by LucasVancoIBM** [comment] 2021-09-30 13:45
I have upgraded to react 17 and still have the problem.
I also noticed that if I zoom on my chrome browser (175% for example) I am able to reproduce the same bug but not in the sandbox somehow.

**Comment by elrumordelaluz** [comment] 2021-09-30 13:47
> chrome browser (175% for example)

We need to find a way to reproduce in a public working example, in order to debug from both sides.

**Comment by danilowanner** [comment] 2021-10-30 07:12
@LucasVancoIBM You must make sure that your package manager indeed resolved the sub-dependency `@reactour/mask` to at least version `0.2.1`.

You find out by using a command like `yarn why @reactour/mask` or looking for the package in your node_modules folder.

Due to the main package `@reactour/tour` defining the dependency as `"@reactour/mask": "*",` your package manager will assume an older version is fine too.

You can use the following, to specifically resolve a newer version of the mask:
- yarn: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
- npm, does not have such functionality yet, but this might help: https://www.npmjs.com/package/npm-force-resolutions

**Comment by elrumordelaluz** [comment] 2021-11-01 21:15
@danilowanner you mean that if packaged are resolved using the latest, should be solved the issue?

Any idea on how to force `@reactour/tour` to get always the latest version of packages?

**Comment by danilowanner** [comment] 2021-11-02 05:35
@elrumordelaluz Yes, I think the described issue can be addressed by updating the mask package. Our team is using the library with `0.2.1` of `@reactour/mask` and the Windows bug is resolved.

I suggest you make a new release of `@reactour/tour` with the dependencies listing a minimum version of `@reactour/mask` and maybe the other packages as well?

Instead of `"*"` you do `"^0.3.1"` (or whichever version is the latest/ most suitable).

**Comment by elrumordelaluz** [comment] 2021-11-02 09:13
Thank you @danilowanner !

So for now I'll close this issue, since should be solved.

**Closed by elrumordelaluz** 2021-11-02 09:13 UTC
