### ISSUE TITLE
func this.setState()  error loop

### ISSUE THREAD

**Issue by zchuhui** [elrumordelaluz/reactour#77] opened 2018-09-14 01:42 UTC
Hi,
I use 

```
<Tour
        steps={steps}
        isOpen={this.state.isTourOpen}
        onRequestClose={this.closeTour} 
        getCurrentStep={()=>this.setState({test:false})}
/>
```

or

```

{
    selector: '[data-tut="reactour__logo"]',
    content: `And this is our cool bus...`,
   action:()=>{ this.setState({test:false}) }
  },
```

In `this.setState({test:false})` code , will report an error in the loop..

help me~~~

**Comment by elrumordelaluz** [comment] 2018-09-14 07:27
@zchuhui in bothn cases you are fireing `setState` in render method that is absolutely avoidable. Render should remains pure. You are creating a big loop doing something like this.

**Comment by zchuhui** [comment] 2018-09-14 07:39
thank you for replying to me ,
 if I want to use Tour to operate state，how to operate?
@elrumordelaluz 

code:

```

  handleCurrentStep = step => {
    console.log(step);

    // here error
    this.setState({
      currentStep: step
    });
  };

  render() {
    const { isTourOpen, isShowingMore } = this.state;
    const accentColor = "#5cb7b7";
    return (
      <div>
        <Demo
          openTour={this.openTour}
          toggleShowMore={this.toggleShowMore}
          isShowingMore={isShowingMore}
        />
        <Tour
          onRequestClose={this.closeTour}
          steps={tourConfig}
          isOpen={isTourOpen}
          maskClassName="mask"
          className="helper"
          rounded={5}
          accentColor={accentColor}
          getCurrentStep={this.handleCurrentStep}
        />
      </div>
    );
  }
```

[![Edit 430oyq8yz7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/430oyq8yz7)

**Comment by elrumordelaluz** [comment] 2018-09-14 07:53
Try doing something a little safer like:

```
    this.setState(prevState => {
      if (this.state.currentStep !== step) {
        return {
          currentStep: step
        };
      }
    });
```

However I am curious about the reason/s. Just to know if the API needs any improves.

**Comment by zchuhui** [comment] 2018-09-14 08:43
thanks, you are good man @elrumordelaluz

**Comment by elrumordelaluz** [comment] 2018-09-14 08:50
Closing. Feel free to re-open in case yo needed.

**Closed by elrumordelaluz** 2018-09-14 08:50 UTC

**Comment by suryacris7** [comment] 2021-06-09 08:05
Hi , regarding the action prop , how am is supposed to handle the State Updates
{
    selector: 'toggle_switch',
    content: `hi hello`,
   action:()=>{ this.setState({toggle : true}) }
  },
  
  Here is my snippet and i want to make my toggle on for this step and also i need to reset all of the state updates either if tour finishes or the user exits the tour

**Comment by elrumordelaluz** [comment] 2021-07-02 13:25
@suryacris7 can you share a code snippet or better a sandbox with a reproduction, please?
