### ISSUE TITLE
restart tour

### ISSUE THREAD

**Issue by jovstern** [elrumordelaluz/reactour#16] opened 2017-09-19 08:29 UTC
Hi man, i was wondering if theirs a clean way to restart the tour when the user finish all the steps?
In our case, we have a button that the user can always come back to the tour and as you know it's start from the step that the user quit and thats fine but, when he got to the final step and he finish or quit, if want to run the tour again, he start from the final step and that's kind of radicals so, what we want is after the last step, restart the tour to the first step.

I used the startAt params and it's working but i got a warning from react (### 

> forceUpdate(...): Cannot update during an existing state transition (such as within `render`...

)
and i kind a think that's a nasty solution.

my code:

 ```
resetTour = () => {
        let {tourStore} = this.props;
        return tourStore.currentStep === this.steps.length ? 0 : undefined
 };
```

`<Tour startAt={this.resetTour()}`

**Comment by elrumordelaluz** [comment] 2017-09-19 09:22
Hi @jovstern I can't reproduce the React warning.
Setting `startAt={0}` doesn't work for you?

Here is my example where every time the user exit the _Tour_, restart from the first `step` (keep in mind that is Array like the `startAt` number, so `0` is the first one.

![startat](https://user-images.githubusercontent.com/784056/30585206-5c3e233a-9d2c-11e7-9a8c-50ff164bb655.gif)

**Comment by jovstern** [comment] 2017-09-24 11:47
It's working but, i think because i run a function every time it's render (to check the final step) console a warning

**Comment by elrumordelaluz** [comment] 2017-09-24 12:53
@jovstern could you share a little bit more code to fully understand where compares the warning and also read the full stack. Now you could **play/edit** the [demo in codesandbox](https://codesandbox.io/s/7kjp4nzv9q?module=%2FApp.js)

**Comment by jovstern** [comment] 2017-09-25 05:12
Unfortunately my code is irrelevant (except the part ill already share) because i work with Mobx states to trigger my tour widget so, 
Ill  try to explain:
my tourStore.currentStep is variable that store the current step.
In the Tour component in the StartAt attr ill check if tourStore.currentStep equal to my steps.length, if it does i restart the steps, meaning i point my startAt to the first step. i'm locking for a cleaner way to restart the steps of the tour when it got to the end and the user want to tour again. hope i was clear :)

**Comment by elrumordelaluz** [comment] 2017-09-25 11:49
So, let me know if I understand well. 
You are firing actions or at least storing the current `step`of the _Tour_ not only internally but in an external `store` (Mobx). It's interesting in your _use-case_, since you are interacting with an external _state managment_ and could compare lot of stuff to improve in `reactour`.

Anyway, I am curious, in case you manage the `currentStep` outside the _Tour_ why and if you tried using the internal `state`. in case you want we could [chat a little more](https://gitter.im/reactour/)

**Comment by jovstern** [comment] 2017-09-26 13:34
You got it right, the reason i work with the Mobx state and not the internal state of the widget it's because i need that some widget in my global app will know about the current state.
Everything work fine but i just don't like the way i "restart the app", maybe after it will be in production (2-3 weeks) i'll send you a link and we can discuss more.

**Comment by elrumordelaluz** [comment] 2017-09-26 20:45
Sure @jovstern please let me know and will continue analysing these points. 
In the meantime I'm thinking in options to control the `state` outside and same for _restart_.

**Comment by elrumordelaluz** [comment] 2019-01-19 00:04
Closing but please feel free to re-open in any case.

**Closed by elrumordelaluz** 2019-01-19 00:04 UTC

**Comment by woodybooy** [comment] 2022-03-30 06:31
@elrumordelaluz hi may i ask you about steps tour
when i reload the page the tour pop up  from left top corner
instead of pop up to where i put the selector

**Comment by elrumordelaluz** [comment] 2022-03-30 07:58
@woodybooy what version of Reactour are you using?

**Comment by itbeginswithi** [comment] 2023-05-19 12:29
@elrumordelaluz, I'm utilizing @reactour/tour v3.4 and assigning a startingStep state to the startAt prop in <ToorProvider startAt={startingSTep}>. The value of startingStep changes after fetching the last visited step from localStorage. However, the startAt prop consistently retains its initial value.
