### ISSUE TITLE
Scrolling issue on Firefox

### ISSUE THREAD

**Issue by jimmydjabali** [elrumordelaluz/reactour#271] opened 2020-07-02 12:14 UTC
Reactour seems to prevents the scrolling on the page. It works well on Chrome
However, on Firefox, it is still possible to scroll the page. And then it may break the layout and display.

**Chrome** (scroll is **impossible**)
![image](https://user-images.githubusercontent.com/10889224/86356381-6da15180-bc6c-11ea-9106-fc41873bba93.png)

**Firefox**  (scroll is **possible**)
![image](https://user-images.githubusercontent.com/10889224/86357421-18fed600-bc6e-11ea-98d1-eb2174aeac2a.png)

**Comment by elrumordelaluz** [comment] 2020-07-02 14:45
Hi @jimmydjabali, thanks for open the _Issue_.

Are you testing at https://reactour.js.org/?

I cant reproduce using _Firefox_ as the main browser.
Let me know,

**Comment by jimmydjabali** [comment] 2020-07-03 22:11
Yes, I am using https://reactour.js.org/
I used Firefox Developer Edition (79.0b3) on the screenshot above.
I tried with regular Firefox (78.0.1), and there's **not** the problem, so probably it's a Firefox bug

**Comment by elrumordelaluz** [comment] 2020-07-04 06:19
I can't reproduce neither using last version of FF DE
<img width="400" alt="Screenshot 2020-07-04 at 08 18 12" src="https://user-images.githubusercontent.com/784056/86506360-fdf7a780-bdce-11ea-9929-3e594cb0b8fb.png">.

I am closing but feel free to reopen in any case.

**Comment by jimmydjabali** [comment] 2020-07-06 09:44
I am on Windows, probably it is the reason of the bug. But I'm not sure it concerns you then :)

**Comment by elrumordelaluz** [comment] 2020-07-06 10:02
Will try also on windows. Mind debug a little to understand if `<body style="overflow: hidden;">` is applied and why doesn't work? Thanks in advance,

**Closed** 2021-09-06 14:10 UTC
Labels: need-more-info
