### ISSUE TITLE
Webpack fails for JS projects from trying to load index.tsx

### ISSUE THREAD

**Issue by yanickrochon** [elrumordelaluz/reactour#493] opened 2022-08-25 13:53 UTC
**Describe the bug**
Not all projects use TypeScript, and not all projects have `.ts`/`.tsx` loaders. This error occurs when using Next.js without TypeScript.

**Expected behavior**
This package should not expect that TypeScript will be available out of the box.

```
error - ./node_modules/@reactour/tour/index.tsx
Module parse failed: Unexpected token (8:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default Tour
| export { Tour, TourContext, TourProvider, useTour }
> export type {
|   StepType,
|   Position,
```

**Comment by elrumordelaluz** [comment] 2022-08-25 13:56
Hi @yanickrochon , thanks for open the _Issue_.

Just founding a fix for this one in the same moment you open this issue.

Let me investigate a little more and came back to you asap.

**Comment by semihraifgurel** [comment] 2022-08-25 17:03
Is there even a way to fix this problem instantly? We can't work for hours because of this. Revert it back until the problem is fixed

**Comment by semihraifgurel** [comment] 2022-08-25 18:08
<img width="424" alt="Ekran Resmi 2022-08-25 21 07 36" src="https://user-images.githubusercontent.com/29544960/186738028-7471790c-4a7c-476b-8126-7921a6fc2f9b.png">
Attached error appears with version 3.0.3

**Comment by elrumordelaluz** [comment] 2022-08-25 18:11
>Attached error appears with version 3.0.3 
I saw, because of this reopened the issue, I'm on it.

The issue seems to be related on `tsup --external react`, try to find the right way to handle it. Help pretty welcome.

**Comment by semihraifgurel** [comment] 2022-08-25 18:16
Can you revert to v3.0.1 until you find a solution?

**Comment by elrumordelaluz** [comment] 2022-08-25 19:51
related https://github.com/egoist/tsup/issues/579

**Comment by elrumordelaluz** [comment] 2022-08-26 08:42
@semihraifgurel @yanickrochon  Could you please try using `@reactour/tour@3.0.5` with a cleaning before `rm -rf node_modules yarn.lock`? Thanks you in advance!

**Comment by gulam-quinn** [comment] 2022-08-26 09:22
@elrumordelaluz version 3.0.5 worked for me. Thanks.

**Comment by semihraifgurel** [comment] 2022-08-26 09:23
It worked, thanks a lot.
<img width="566" alt="Ekran Resmi 2022-08-26 12 22 47" src="https://user-images.githubusercontent.com/29544960/186872626-b09e8ff7-2483-4d20-9099-1308e310d178.png">

**Comment by elrumordelaluz** [comment] 2022-08-26 09:26
Great! Thank you for following and helping to solve the issue!

**Comment by jmwakz99** [comment] 2022-08-26 10:02
Hello I am getting this error
`Can't import the named export 'FocusScope' from non EcmaScript module (only default export is available)`

**Comment by elrumordelaluz** [comment] 2022-08-26 10:12
> Hello I am getting this error `Can't import the named export 'FocusScope' from non EcmaScript module (only default export is available)`

From which file? can you share some more info? context, if is ts project?

**Comment by elrumordelaluz** [comment] 2022-08-26 11:32
> This is causing my builds to fail. Is there a stable version I can use?

Should be `3.0.1`

I am sorry for those errors.

**Comment by yanickrochon** [comment] 2022-08-26 12:10
@elrumordelaluz everything is fine with `3.0.5`! Good job!

**Comment by shubhrasachdev** [comment] 2022-08-26 23:10
> > This is causing my builds to fail. Is there a stable version I can use?
> 
> Should be `3.0.1`
> 
> I am sorry for those errors.

Hey @elrumordelaluz , still seeing this same error in 3.0.1.

**Comment by elrumordelaluz** [comment] 2022-08-27 10:39
>Hey @elrumordelaluz , still seeing this same error in 3.0.1.

Take a look to the replies on #498, I think could be a fast and temporary workaround.
Meanwhile I am working to solve the packages resolutions issue.

**Comment by elrumordelaluz** [comment] 2022-08-28 21:20
For those who were having issues with _named export from non EcmaScript module_, can you please upgrade version/s to check if the issue is solved on your end? Thanks!

**Comment by shubhrasachdev** [comment] 2022-08-29 05:04
Hey @elrumordelaluz , upgraded to @reactour/tour version 3.0.1. I am seeing this issue again:

```
./node_modules/@reactour/tour/dist/index.mjs
Can't import the named export 'Mask' from non EcmaScript module (only default export is available)
```

**Comment by elrumordelaluz** [comment] 2022-08-29 06:27
thank you @shubhrasachdev, mind making `rm -rf node_modules yarn.lock` (or npm lock file) and then install again?

**Comment by shubhrasachdev** [comment] 2022-08-29 07:02
Tried after cleaning, the issue is still occurring. Any other things I can try?

**Comment by elrumordelaluz** [comment] 2022-08-29 07:08
can you share more info related on your environment and project?

**Comment by shubhrasachdev** [comment] 2022-08-29 07:19
This is the env and project config I am working with:
OS: Windows 10
OS build: 19044.1889
Node.js Version: 16.15.0
React Version: 18.1.0
@reactour/tour Version: 3.1.0

Let me know if nay additional info is required.

**Comment by elrumordelaluz** [comment] 2022-08-29 07:21
are you using CRA or in which way are you transpiling?

**Comment by shubhrasachdev** [comment] 2022-08-29 07:30
From what I can tell, its CRA. I run the `npm run start` command, which as described in my package.json, runs `react-scripts start`

**Comment by elrumordelaluz** [comment] 2022-08-29 07:42
What happens if you do `npm why @reactour/mask`

**Comment by elrumordelaluz** [comment] 2022-08-29 07:43
Also, can you search please for "@reactour" in your `package-lock.json `?

**Comment by shubhrasachdev** [comment] 2022-08-29 07:49
Hey @elrumordelaluz , I noticed I was using react-scripts 3.4.4. I just now upgraded to 5.0.1, and now it is running as expected.

As for the info you asked from my package-lock.json - 
"node_modules/@reactour/tour": {
      "version": "3.1.0",
      "resolved": "...",
      "integrity": "...",
      "license": "MIT",
      "dependencies": {
        "@reactour/mask": "*",
        "@reactour/popover": "*",
        "@reactour/utils": "*"
      },
      "peerDependencies": {
        "react": "16.x || 17.x || 18.x"
      }
    }

**Comment by elrumordelaluz** [comment] 2022-08-29 07:50
> I just now upgraded to 5.0.1, and now it is running as expected.

great!

Curious about this command:

> What happens if you do npm why @reactour/mask?

Thanks for all the information!

**Comment by shubhrasachdev** [comment] 2022-08-29 08:12
Here's the response from `npm why @reactour/mask`:
```
@reactour/mask@1.0.4
node_modules/@reactour/mask
  @reactour/mask@"*" from @reactour/tour@3.1.0
  node_modules/@reactour/tour
    @reactour/tour@"^3.1.0" from the root project

```

**Comment by elrumordelaluz** [comment] 2022-08-29 08:18
Seems to resolve well. Thanks again!

**Comment by elrumordelaluz** [comment] 2022-08-29 08:20
Since the small issues described after the author closes the main one seems to be solve, I am closing this _issue_, but feel free create a new one with specific information. Thanks again to you all!

**Closed by elrumordelaluz** 2022-08-29 08:20 UTC
Labels: bug, help-welcome
