### ISSUE TITLE
how to change of overlay of background , using maskClassName?

### ISSUE THREAD

**Issue by virinchi-manepalli-trysolvio** [elrumordelaluz/reactour#366] opened 2021-09-10 15:19 UTC
can you tell an example of how to change the color of the background? , I didn't understand how to pass color to maskClassName
I want the background to be transparent  same as demo

![image](https://user-images.githubusercontent.com/78961690/132876923-aa9d5a6c-b1c3-46a9-8e67-60834d8edb13.png)

**Comment by elrumordelaluz** [comment] 2021-09-10 16:29
Hi @virinchi-manepalli-trysolvio, thanks for open the _Issue_.

What version are you using?

**Comment by virinchi-manepalli-trysolvio** [comment] 2021-09-11 04:20
the latest version only >16.8version (hooks).
I m using this in nextjs, 
I have a question is this library supports the latest version of react and next js?

btw Thanks for the very quick reply :)

**Comment by elrumordelaluz** [comment] 2021-09-11 12:10
The version `v2` is now under `@reactour/tour`, and supports all the latest versions. [Here the docs](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour) and [here a demo customizing styles](https://reactour.vercel.app/#styles)

**Comment by virinchi-manepalli-trysolvio** [comment] 2021-09-15 17:10
![Screenshot (433)](https://user-images.githubusercontent.com/78961690/133478583-043c6408-0394-4e8d-82b6-3216e8aff4b1.png)

Thanks @elrumordelaluz   now I m able to customize overlay.
but I don't know why my mask position is  misplacing, could please tell how to fix this issue? i m wrapping selector correctly

**Comment by elrumordelaluz** [comment] 2021-09-15 19:18
@virinchi-manepalli-trysolvio could you please share the ´styles´ object?

**Comment by virinchimanepalli** [comment] 2021-09-18 05:21
sure @elrumordelaluz 
![Screenshot (440)](https://user-images.githubusercontent.com/50209716/133873737-dfc78723-d61c-4616-9473-549a115e51cd.png)

**Comment by virinchimanepalli** [comment] 2021-09-18 05:46
also, I m trying to get a walkthrough for the list of items in the sidebar.
![Screenshot (443)](https://user-images.githubusercontent.com/50209716/133874553-0e63e77f-12da-4261-ab22-d376de3aed13.png)

 I m mapping the list of items child component for displaying data in the above manner.
the problem is I want to get a walkthrough for each item in the side menu .

![Screenshot (441)](https://user-images.githubusercontent.com/50209716/133877315-831bffa9-210c-4bf4-a245-478bdc280344.png)

if do like this, the stepper is coming out to center, i think, the selector is unable to find HTML element if I iterate over a component.

can you help me with a better approach?

ref: items array I m passing 
  {
    name: "Library",
    href: "/library",
    as: "/library",
    icon: LibraryIcon,
    current: false,
    selector: "reactour__library",
  }[]


Thanks in advance

**Comment by elrumordelaluz** [comment] 2021-09-20 12:29
The position of the _Mask_ should be controlled by the `selector` of this specific step. 

Mind creating a minimal reproduction in a sandbox?

Thanksn

**Comment by elrumordelaluz** [comment] 2021-10-01 10:27
Closing but feel free to re-open in any case.

**Closed by elrumordelaluz** 2021-10-01 10:27 UTC
