### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by lucienbl** [elrumordelaluz/reactour#71] opened 2018-08-26 19:21 UTC
Hi 😃 

I tried to use this module but I always get this error 😄 : 
`SyntaxError: import declarations may only appear at top level of a module`

I looked in the module files and yes the imports are never at the top of file 🤔 So I put all the imports in every file at the top and it's still not working, any idea ? 😃 

Thanks in advance,
lucienbl

**Comment by elrumordelaluz** [comment] 2018-08-26 20:58
Hi @lucienbl,
I am sorry to heard that. Could you please explain a little more how you are installing/using `reactour`, maybe with a code snippet or sharing a repo.
I am happy to help you set this up.

**Comment by lucienbl** [comment] 2018-08-27 12:18
Hmm I installed and used it exactly like in the documentation 😄 
Since I had this error I tried another "Tour" repo so I don't have any "real" snippet right now.

Here my steps:
1. `yarn add reactour styled-components`
2. Global structure of my file :
 ```javascript
import Tour from 'reactour';

const steps = [
  {
    selector: '.first-step',
    content: 'This is my first Step',
  },
]

class App extends Component {

  constructor(props) {
    super(props);
  
    this.state = {
     isTourOpen: true,
    };

  render  (
    <div>
      <div className="first-step">Step 1 here</div>
      { /* other stuff */}
      <Tour
        steps={steps}
        isOpen={this.state.isTourOpen}
        onRequestClose={() => this.setState({ isTourOpen: false })} />
    </div>
  )
}
```

**Comment by elrumordelaluz** [comment] 2018-08-27 14:33
Could you please try with [this simple reproduction](https://github.com/elrumordelaluz/reactour-test) of your code?

**Comment by elrumordelaluz** [comment] 2018-08-27 16:51
I thought about something similar.

Closing, since seems an _issue_ no related to `reactour`.

Feel free to re-open / open another _issue_ in any case.

**Closed by elrumordelaluz** 2018-08-27 16:51 UTC
